

<h1> Contact </h1>

<div class="container">

<form action="/PHP-Framework-project/show-contact" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Prenom</label>
        <input type="text"  name="firstname" class="form-control">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Nom</label>
        <input type="text" name="lastname" class="form-control" >
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
