<h1> Bienvenue dans l'accueil </h1>

<br>
<br>

<a href="/PHP-Framework-project/contact">
    <button class="btn btn-primary"> Aller page contact</button>
</a>

<br><br>

<a href="/PHP-Framework-project/show-all-contact">
    <button class="btn btn-primary">  Afficher tous les contacts </button>
</a>

<br><br>

<a href="/PHP-Framework-project/contact/2">
    <button class="btn btn-primary">  Affiche le contact avec l'id 2 </button>
</a>

<br><br>

<a href="/PHP-Framework-project/cette-page-existe-pas">
    <button class="btn btn-primary">  Afficher Erreur 'Sorry , page not found ' </button>
</a>

<br><br>

<a href="/PHP-Framework-project/show-contact">
    <button class="btn btn-primary"> Afficher Erreur methode http </button>
</a>



