<!doctype html>
<html lang="en">
<head>
    <meta charset="<?= $this->getCharset() ?? 'UTF-8' ?>" >
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> <?= $this->getTitle() ?></title>
    <?php

    foreach ($this->getStyles() as $style) {
        echo '<link rel="stylesheet" href="' .$style . '">';
    }
    ?>
</head>

<body>

<?php
require 'body.phtml';
require 'footer.phtml'
?>
</body>

</html>
